// equipmaster.js — Pre-seeded equipment type library from EQUIPMASTER.xlsx
// 174 equipment types across 13 categories

export const EQUIPMASTER = [
  {
    "equipment_type": "Air Handling Unit",
    "category": "HVAC",
    "tag_prefix": "AHU",
    "manufacturers": "Trane, Carrier, Daikin, York, Lennox, Temtrol, Engineered Air, Aaon, ClimateCraft, Huntair, Ventrol, Greenheck, Nortek, McQuay, Systemair",
    "quarterly_std_hours": 1.5,
    "annual_std_hours": 6.0,
    "belt_size": "varies",
    "filter_size": "varies",
    "filter_type": "Pleated / Bag / HEPA",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Central air unit that heats, cools, filters, and moves air through duct systems. Includes filters, coils, dampers, belts, bearings, actuators, and controls.",
    "semi_annual_std_hours": 3.0,
    "monthly_std_hours": 0.5
  },
  {
    "equipment_type": "Rooftop Unit",
    "category": "HVAC",
    "tag_prefix": "RTU",
    "manufacturers": "Carrier, Lennox, Trane, York, Aaon, Daikin, Rheem, ICP, Bryant, Tempstar, Goodman, Nordyne, Fujitsu, Hitachi",
    "quarterly_std_hours": 1.25,
    "annual_std_hours": 5.0,
    "belt_size": "varies",
    "filter_size": "varies",
    "filter_type": "Pleated",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Packaged rooftop HVAC unit with DX cooling and gas/electric heat. Often includes economizer, combustion system, filters, and supply fan.",
    "semi_annual_std_hours": 2.5,
    "monthly_std_hours": 0.42
  },
  {
    "equipment_type": "Fan Coil Unit",
    "category": "HVAC",
    "tag_prefix": "FCU",
    "manufacturers": "Daikin, Carrier, Trane, FirstCo, IEC, Williams, EnviroTec, Whalen, McQuay, Titus, Price",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 1.5,
    "belt_size": "small",
    "filter_size": "1\u20132\"",
    "filter_type": "Pleated",
    "lubricant_type": "None / sealed",
    "electrical_data": "",
    "description": "Local terminal air unit with hydronic or DX coil used for zone heating and cooling.",
    "semi_annual_std_hours": 0.83,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Variable Air Volume Box",
    "category": "HVAC",
    "tag_prefix": "VAV",
    "manufacturers": "Price, Titus, Nailor, Johnson Controls, Honeywell, Siemens, Krueger, Metal Industries, EnviroTec",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Modulates airflow to zone. May include reheat coil, actuator, and control board.",
    "semi_annual_std_hours": 0.42,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Energy Recovery Ventilator",
    "category": "HVAC",
    "tag_prefix": "ERV",
    "manufacturers": "RenewAire, Daikin, Trane, Greenheck, Fantech, Venmar, Lifebreath, Systemair, Broan, CaptiveAire",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.5,
    "belt_size": "varies",
    "filter_size": "varies",
    "filter_type": "Pleated",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Transfers heat and moisture between exhaust and intake air streams.",
    "semi_annual_std_hours": 1.33,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Heat Recovery Ventilator",
    "category": "HVAC",
    "tag_prefix": "HRV",
    "manufacturers": "Lifebreath, Fantech, Venmar, Broan, Systemair, Panasonic, Aldes",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "varies",
    "filter_type": "Pleated",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Transfers heat only between exhaust and intake air streams.",
    "semi_annual_std_hours": 1.17,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Make Up Air Unit",
    "category": "HVAC",
    "tag_prefix": "MUA",
    "manufacturers": "Engineered Air, CaptiveAire, Greenheck, Aaon, Addison, Cambridge, Hastings, Modine, Reznor, Valent",
    "quarterly_std_hours": 1.5,
    "annual_std_hours": 5.0,
    "belt_size": "varies",
    "filter_size": "varies",
    "filter_type": "Pleated",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Supplies tempered outside air to building to replace exhaust air. Includes burner, fan, filters, and dampers.",
    "semi_annual_std_hours": 2.67,
    "monthly_std_hours": 0.5
  },
  {
    "equipment_type": "Exhaust Fan",
    "category": "HVAC",
    "tag_prefix": "EF",
    "manufacturers": "Greenheck, Loren Cook, PennBarry, Twin City, Cook, Systemair, Fantech, Continental Fan, Acme",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Removes air from space. Includes motor, bearings, wheel, and belt if applicable.",
    "semi_annual_std_hours": 0.83,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Inline Fan",
    "category": "HVAC",
    "tag_prefix": "IF",
    "manufacturers": "Fantech, Greenheck, Systemair, S&P, Cook, Twin City, PennBarry",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Duct mounted fan for exhaust or supply.",
    "semi_annual_std_hours": 0.83,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Supply Fan",
    "category": "HVAC",
    "tag_prefix": "SF",
    "manufacturers": "Greenheck, Twin City, Loren Cook, PennBarry, Cook, Chicago Blower, NYB",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.0,
    "belt_size": "varies",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Moves supply air through duct system.",
    "semi_annual_std_hours": 1.17,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Return Fan",
    "category": "HVAC",
    "tag_prefix": "RF",
    "manufacturers": "Greenheck, Twin City, Cook, Loren Cook, PennBarry",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.0,
    "belt_size": "varies",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Returns air to AHU or system.",
    "semi_annual_std_hours": 1.17,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Unit Heater",
    "category": "HVAC",
    "tag_prefix": "UH",
    "manufacturers": "Reznor, Modine, Sterling, Engineered Air, Beacon Morris, Lennox, Cambridge",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Suspended heater using gas, electric, or hot water.",
    "semi_annual_std_hours": 0.83,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Electric Heater",
    "category": "HVAC",
    "tag_prefix": "EH",
    "manufacturers": "Stelpro, Qmark, Indeeco, Thermolec, King, Markel, Chromalox",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Electric resistance heater for duct or space heating.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Chiller",
    "category": "HVAC",
    "tag_prefix": "CH",
    "manufacturers": "Trane, Carrier, York, Daikin, McQuay, Multistack, Smardt, Dunham Bush, Climaveneta",
    "quarterly_std_hours": 2.0,
    "annual_std_hours": 10.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "",
    "description": "Produces chilled water for cooling system. Includes compressor, condenser, evaporator.",
    "semi_annual_std_hours": 4.67,
    "monthly_std_hours": 0.67
  },
  {
    "equipment_type": "Cooling Tower",
    "category": "HVAC",
    "tag_prefix": "CT",
    "manufacturers": "BAC, Marley, Evapco, Delta, Recold, Baltimore, Paharpur",
    "quarterly_std_hours": 2.0,
    "annual_std_hours": 8.0,
    "belt_size": "varies",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Rejects heat from condenser water loop to atmosphere.",
    "semi_annual_std_hours": 4.0,
    "monthly_std_hours": 0.67
  },
  {
    "equipment_type": "Condensing Unit",
    "category": "HVAC",
    "tag_prefix": "CU",
    "manufacturers": "Carrier, Trane, Lennox, Copeland, Tecumseh, Bitzer, Heatcraft, Danfoss, Embraco",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "",
    "description": "Outdoor refrigeration condensing section.",
    "semi_annual_std_hours": 1.33,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Heat Pump",
    "category": "HVAC",
    "tag_prefix": "HP",
    "manufacturers": "Mitsubishi, Daikin, Fujitsu, LG, Samsung, Carrier, Trane, Bosch, Panasonic",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.5,
    "belt_size": "",
    "filter_size": "varies",
    "filter_type": "Pleated",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "DX heat/cool system.",
    "semi_annual_std_hours": 1.33,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "VRF Outdoor",
    "category": "HVAC",
    "tag_prefix": "VRF",
    "manufacturers": "Mitsubishi, Daikin, LG, Samsung, Toshiba, Fujitsu, Hitachi, Panasonic",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "",
    "description": "Multi-zone refrigerant system outdoor unit.",
    "semi_annual_std_hours": 1.67,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "VRF Indoor",
    "category": "HVAC",
    "tag_prefix": "IDU",
    "manufacturers": "Mitsubishi, Daikin, LG, Samsung, Fujitsu, Toshiba",
    "quarterly_std_hours": 0.4,
    "annual_std_hours": 1.25,
    "belt_size": "",
    "filter_size": "small",
    "filter_type": "Pleated",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Indoor VRF terminal unit.",
    "semi_annual_std_hours": 0.68,
    "monthly_std_hours": 0.13
  },
  {
    "equipment_type": "CRAC Unit",
    "category": "HVAC",
    "tag_prefix": "CRAC",
    "manufacturers": "Liebert, Stulz, Schneider, Vertiv, Data Aire",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 4.0,
    "belt_size": "varies",
    "filter_size": "varies",
    "filter_type": "Pleated",
    "lubricant_type": "Oil / grease",
    "electrical_data": "",
    "description": "Precision cooling for server rooms.",
    "semi_annual_std_hours": 2.0,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Humidifier",
    "category": "HVAC",
    "tag_prefix": "HUM",
    "manufacturers": "Nortec, Condair, Armstrong, DriSteem, Carel",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Adds humidity to air system.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Dehumidifier",
    "category": "HVAC",
    "tag_prefix": "DHUM",
    "manufacturers": "Dectron, Desert Aire, Munters, PoolPak, Seresco",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.5,
    "belt_size": "varies",
    "filter_size": "varies",
    "filter_type": "Pleated",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Removes moisture from air.",
    "semi_annual_std_hours": 1.33,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Kitchen Exhaust Fan",
    "category": "HVAC",
    "tag_prefix": "KEF",
    "manufacturers": "CaptiveAire, Halton, Greenheck, Gaylord, Accurex",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "varies",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Exhaust for cooking vapors and grease.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Kitchen MUA",
    "category": "HVAC",
    "tag_prefix": "KMUA",
    "manufacturers": "CaptiveAire, Halton, Greenheck, Engineered Air",
    "quarterly_std_hours": 1.25,
    "annual_std_hours": 4.0,
    "belt_size": "varies",
    "filter_size": "varies",
    "filter_type": "Pleated",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Supplies replacement air for kitchen exhaust.",
    "semi_annual_std_hours": 2.17,
    "monthly_std_hours": 0.42
  },
  {
    "equipment_type": "Stair Press Fan",
    "category": "HVAC",
    "tag_prefix": "SPF",
    "manufacturers": "Greenheck, Twin City, Cook, PennBarry",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.0,
    "belt_size": "varies",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Pressurizes stairwell during fire event.",
    "semi_annual_std_hours": 1.17,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Smoke Exhaust Fan",
    "category": "HVAC",
    "tag_prefix": "SEF",
    "manufacturers": "Greenheck, Twin City, Cook, PennBarry",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 2.0,
    "belt_size": "varies",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Smoke removal system.",
    "semi_annual_std_hours": 1.17,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Hot Water Boiler",
    "category": "Hydronic",
    "tag_prefix": "BLR",
    "manufacturers": "Viessmann, Lochinvar, Raypak, Cleaver-Brooks, Weil-McLain, NTI, IBC, Bosch, Buderus, AERCO, Laars, Fulton",
    "quarterly_std_hours": 2.0,
    "annual_std_hours": 8.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil / grease",
    "electrical_data": "",
    "description": "Produces heating hot water for hydronic system. Includes burner, heat exchanger, gas train, safeties.",
    "semi_annual_std_hours": 4.0,
    "monthly_std_hours": 0.67
  },
  {
    "equipment_type": "Steam Boiler",
    "category": "Hydronic",
    "tag_prefix": "SBLR",
    "manufacturers": "Cleaver-Brooks, Fulton, Weil-McLain, Columbia, Burnham, Miura",
    "quarterly_std_hours": 2.0,
    "annual_std_hours": 10.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil / grease",
    "electrical_data": "",
    "description": "Produces steam for heating or process. Requires blowdown, combustion testing, safety checks.",
    "semi_annual_std_hours": 4.67,
    "monthly_std_hours": 0.67
  },
  {
    "equipment_type": "Condensing Boiler",
    "category": "Hydronic",
    "tag_prefix": "CBLR",
    "manufacturers": "Viessmann, Lochinvar, NTI, IBC, Bosch, Buderus, AERCO, Triangle Tube, Navien",
    "quarterly_std_hours": 1.5,
    "annual_std_hours": 6.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "None / oil",
    "electrical_data": "",
    "description": "High efficiency boiler with condensate system and combustion control.",
    "semi_annual_std_hours": 3.0,
    "monthly_std_hours": 0.5
  },
  {
    "equipment_type": "Chilled Water Chiller",
    "category": "Hydronic",
    "tag_prefix": "CH",
    "manufacturers": "Trane, Carrier, York, Daikin, McQuay, Multistack, Smardt, Dunham-Bush, Climaveneta",
    "quarterly_std_hours": 2.0,
    "annual_std_hours": 10.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "",
    "description": "Produces chilled water for cooling coils.",
    "semi_annual_std_hours": 4.67,
    "monthly_std_hours": 0.67
  },
  {
    "equipment_type": "Plate Heat Exchanger",
    "category": "Hydronic",
    "tag_prefix": "HX",
    "manufacturers": "Alfa Laval, SWEP, Bell & Gossett, Armstrong, Tranter, API, GEA",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 4.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Transfers heat between two water loops without mixing fluids.",
    "semi_annual_std_hours": 2.0,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Shell & Tube Heat Exchanger",
    "category": "Hydronic",
    "tag_prefix": "HE",
    "manufacturers": "Bell & Gossett, Armstrong, Taco, API, Alfa Laval, Xylem",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 5.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Heat transfer through tube bundle. Often used for DHW or isolation loops.",
    "semi_annual_std_hours": 2.33,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Heating Water Pump",
    "category": "Hydronic",
    "tag_prefix": "HWP",
    "manufacturers": "Grundfos, Taco, Armstrong, Bell & Gossett, Wilo, Xylem, KSB",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Circulates heating water through system.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Chilled Water Pump",
    "category": "Hydronic",
    "tag_prefix": "CHWP",
    "manufacturers": "Grundfos, Armstrong, Taco, B&G, Wilo, Xylem",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Circulates chilled water loop.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Condenser Water Pump",
    "category": "Hydronic",
    "tag_prefix": "CWP",
    "manufacturers": "Grundfos, Armstrong, Taco, Bell & Gossett, Wilo",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Circulates water between chiller and cooling tower.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Secondary Pump",
    "category": "Hydronic",
    "tag_prefix": "SP",
    "manufacturers": "Grundfos, Taco, Armstrong, B&G, Wilo",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Serves secondary loop.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Primary Pump",
    "category": "Hydronic",
    "tag_prefix": "PP",
    "manufacturers": "Grundfos, Taco, Armstrong, B&G, Wilo",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Primary loop circulation pump.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Booster Pump",
    "category": "Hydronic",
    "tag_prefix": "BP",
    "manufacturers": "Grundfos, Armstrong, Taco, Xylem, Patterson, Aurora",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Increases pressure in loop or system.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Circulator Pump",
    "category": "Hydronic",
    "tag_prefix": "P",
    "manufacturers": "Taco, Grundfos, B&G, Armstrong",
    "quarterly_std_hours": 0.4,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "",
    "description": "Small hydronic pump for zone or branch.",
    "semi_annual_std_hours": 0.77,
    "monthly_std_hours": 0.13
  },
  {
    "equipment_type": "Expansion Tank",
    "category": "Hydronic",
    "tag_prefix": "ET",
    "manufacturers": "Amtrol, Wessels, Taco, B&G, Armstrong, Watts",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Absorbs thermal expansion in closed loop.",
    "semi_annual_std_hours": 0.83,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Compression Tank",
    "category": "Hydronic",
    "tag_prefix": "CTK",
    "manufacturers": "Wessels, Taco, B&G, Armstrong",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Older style expansion tank.",
    "semi_annual_std_hours": 0.83,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Air Separator",
    "category": "Hydronic",
    "tag_prefix": "AS",
    "manufacturers": "Spirotherm, Taco, Bell & Gossett, Armstrong, Caleffi",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Removes air from loop.",
    "semi_annual_std_hours": 0.42,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Dirt Separator",
    "category": "Hydronic",
    "tag_prefix": "DS",
    "manufacturers": "Spirotherm, Caleffi, Taco, Armstrong",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Removes debris from loop.",
    "semi_annual_std_hours": 0.42,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Hydraulic Separator",
    "category": "Hydronic",
    "tag_prefix": "HS",
    "manufacturers": "Caleffi, Taco, Viessmann, Spirotherm",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Separates primary/secondary flow.",
    "semi_annual_std_hours": 0.42,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Buffer Tank",
    "category": "Hydronic",
    "tag_prefix": "BT",
    "manufacturers": "Axiom, Lochinvar, Amtrol, Wessels, Taco",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Stabilizes loop temperature.",
    "semi_annual_std_hours": 0.83,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Glycol Feeder",
    "category": "Hydronic",
    "tag_prefix": "GF",
    "manufacturers": "Axiom, Sentinel, Precision Hydronics, Watts",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Maintains glycol pressure.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Chemical Feeder",
    "category": "Hydronic",
    "tag_prefix": "CF",
    "manufacturers": "Neptune, Sentinel, Axiom, Nalco",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Adds treatment chemicals.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Pot Feeder",
    "category": "Hydronic",
    "tag_prefix": "PF",
    "manufacturers": "Axiom, Neptune, Sentinel",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Manual chemical addition.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Mixing Valve",
    "category": "Hydronic",
    "tag_prefix": "MV",
    "manufacturers": "Caleffi, Watts, Honeywell, Leonard, Armstrong",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Controls supply water temperature.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Balancing Valve",
    "category": "Hydronic",
    "tag_prefix": "BV",
    "manufacturers": "B&G, Caleffi, TA, Griswold, Watts",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Controls loop flow.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Control Valve",
    "category": "Hydronic",
    "tag_prefix": "CV",
    "manufacturers": "Belimo, Honeywell, Siemens, Johnson Controls, Danfoss",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Modulates water flow.",
    "semi_annual_std_hours": 0.35,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Zone Valve",
    "category": "Hydronic",
    "tag_prefix": "ZV",
    "manufacturers": "Taco, Honeywell, Belimo, Danfoss",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Opens/closes zone flow.",
    "semi_annual_std_hours": 0.27,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Triple Duty Valve",
    "category": "Hydronic",
    "tag_prefix": "TDV",
    "manufacturers": "Taco, B&G, Armstrong, Watts",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Pump isolation / check / balance.",
    "semi_annual_std_hours": 0.42,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Strainer",
    "category": "Hydronic",
    "tag_prefix": "STR",
    "manufacturers": "Watts, Apollo, Mueller, Victaulic",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Debris protection.",
    "semi_annual_std_hours": 0.35,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Low Water Cutoff",
    "category": "Hydronic",
    "tag_prefix": "LWCO",
    "manufacturers": "McDonnell & Miller, Hydrolevel, Safgard",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Boiler safety device.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Condensate Neutralizer",
    "category": "Hydronic",
    "tag_prefix": "CN",
    "manufacturers": "RectorSeal, Diversitech, JJM, Watts",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Neutralizes acidic condensate.",
    "semi_annual_std_hours": 0.27,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Domestic Hot Water Heater",
    "category": "Plumbing",
    "tag_prefix": "WH",
    "manufacturers": "AO Smith, Bradford White, Rheem, John Wood, Navien, Rinnai, Noritz, Bosch, Lochinvar, State",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 4.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120/240/480V / Gas",
    "description": "Produces domestic hot water for fixtures and suites.",
    "semi_annual_std_hours": 2.0,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Storage Tank",
    "category": "Plumbing",
    "tag_prefix": "DHWT",
    "manufacturers": "AO Smith, Lochinvar, Bradford White, Rheem, Amtrol, Wessels, Vaughn",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Stores heated potable water.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Indirect Water Heater",
    "category": "Plumbing",
    "tag_prefix": "IWH",
    "manufacturers": "Viessmann, Lochinvar, SuperStor, Triangle Tube, NTI",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Tank heated from boiler loop.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Tankless Water Heater",
    "category": "Plumbing",
    "tag_prefix": "TWH",
    "manufacturers": "Navien, Rinnai, Noritz, Bosch, Takagi, IBC",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V / Gas",
    "description": "On demand water heating appliance.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "DHW Recirculation Pump",
    "category": "Plumbing",
    "tag_prefix": "HWRP",
    "manufacturers": "Grundfos, Taco, Armstrong, Bell & Gossett, Wilo",
    "quarterly_std_hours": 0.4,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "120/208/460V",
    "description": "Circulates domestic hot water loop.",
    "semi_annual_std_hours": 0.77,
    "monthly_std_hours": 0.13
  },
  {
    "equipment_type": "Domestic Booster Pump",
    "category": "Plumbing",
    "tag_prefix": "DBP",
    "manufacturers": "Grundfos, Armstrong, Taco, Xylem, Aurora, Patterson",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "208/460V",
    "description": "Maintains domestic water pressure.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Booster Pump Package",
    "category": "Plumbing",
    "tag_prefix": "BPS",
    "manufacturers": "Grundfos, Armstrong, Xylem, Patterson, Aurora, Wilo",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 4.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "208/460V",
    "description": "Multi pump pressure system.",
    "semi_annual_std_hours": 2.0,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Pressure Reducing Valve",
    "category": "Plumbing",
    "tag_prefix": "PRV",
    "manufacturers": "Watts, Apollo, Honeywell, Cash Acme, Wilkins",
    "quarterly_std_hours": 0.2,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Reduces domestic pressure.",
    "semi_annual_std_hours": 0.38,
    "monthly_std_hours": 0.07
  },
  {
    "equipment_type": "Backflow Preventer",
    "category": "Plumbing",
    "tag_prefix": "BFP",
    "manufacturers": "Watts, Wilkins, Febco, Ames, Zurn",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Prevents reverse flow contamination.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Water Softener",
    "category": "Plumbing",
    "tag_prefix": "WS",
    "manufacturers": "Culligan, Canature, Pentair, EcoWater, Clack",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "cartridge",
    "filter_type": "resin",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Removes hardness minerals.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Sand Filter",
    "category": "Plumbing",
    "tag_prefix": "SF",
    "manufacturers": "Pentair, Culligan, Watts, Hayward",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "varies",
    "filter_type": "media",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Removes sediment.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Cartridge Filter Housing",
    "category": "Plumbing",
    "tag_prefix": "CFH",
    "manufacturers": "Pentek, Watts, 3M, Culligan, Pentair",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "varies",
    "filter_type": "cartridge",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Water filtration housing.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "UV Sterilizer",
    "category": "Plumbing",
    "tag_prefix": "UV",
    "manufacturers": "Trojan, Viqua, Wedeco, Sterilight",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Disinfection of water.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Reverse Osmosis",
    "category": "Plumbing",
    "tag_prefix": "RO",
    "manufacturers": "Watts, Culligan, Pentair, AXEON, Puretec",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "varies",
    "filter_type": "membrane",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Removes dissolved solids.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Water Meter",
    "category": "Plumbing",
    "tag_prefix": "WM",
    "manufacturers": "Neptune, Sensus, Badger, Kamstrup, Itron",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Measures water usage.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Gas Water Heater",
    "category": "Plumbing",
    "tag_prefix": "GWH",
    "manufacturers": "AO Smith, Rheem, Bradford White, Lochinvar, Raypak",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "Gas / 120V",
    "description": "Gas fired water heater.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Electric Water Heater",
    "category": "Plumbing",
    "tag_prefix": "EWH",
    "manufacturers": "Rheem, AO Smith, John Wood, Bradford White",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "240/480V",
    "description": "Electric water heater.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Sewage Ejector Pump",
    "category": "Plumbing",
    "tag_prefix": "SEP",
    "manufacturers": "Liberty, Zoeller, Myers, Barnes, Hydromatic",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil / grease",
    "electrical_data": "120/208/460V",
    "description": "Pumps sewage from basin.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Sewage Pump Package",
    "category": "Plumbing",
    "tag_prefix": "SPP",
    "manufacturers": "Liberty, Zoeller, Myers, Flygt, Hydromatic",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 4.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil / grease",
    "electrical_data": "208/460V",
    "description": "Duplex sewage pump system.",
    "semi_annual_std_hours": 2.0,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Grinder Pump",
    "category": "Plumbing",
    "tag_prefix": "GP",
    "manufacturers": "Liberty, Zoeller, Myers, EOne",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "208/460V",
    "description": "Macerates solids.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Lift Station",
    "category": "Plumbing",
    "tag_prefix": "LS",
    "manufacturers": "Flygt, Liberty, Zoeller, Myers, Xylem",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 5.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "208/460V",
    "description": "Wastewater pumping station.",
    "semi_annual_std_hours": 2.33,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Condensate Pump",
    "category": "Plumbing",
    "tag_prefix": "CP",
    "manufacturers": "Little Giant, Diversitech, Rectorseal, Aspen",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Pumps condensate.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Grease Interceptor",
    "category": "Plumbing",
    "tag_prefix": "GI",
    "manufacturers": "Schier, Zurn, Josam, Watts, Rockford",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Separates grease.",
    "semi_annual_std_hours": 1.33,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Grease Trap",
    "category": "Plumbing",
    "tag_prefix": "GT",
    "manufacturers": "Schier, Zurn, Josam, Canplas",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Local grease separation.",
    "semi_annual_std_hours": 1.33,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Oil Interceptor",
    "category": "Plumbing",
    "tag_prefix": "OI",
    "manufacturers": "Zurn, Josam, Wade, Highland Tank",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Separates oil.",
    "semi_annual_std_hours": 1.33,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Solids Interceptor",
    "category": "Plumbing",
    "tag_prefix": "SI",
    "manufacturers": "Zurn, Schier, Josam",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Captures solids.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Acid Neutralizer",
    "category": "Plumbing",
    "tag_prefix": "ANT",
    "manufacturers": "Zurn, Watts, Schier, Josam",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Neutralizes acid waste.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Plaster Interceptor",
    "category": "Plumbing",
    "tag_prefix": "PI",
    "manufacturers": "Zurn, Josam, Schier",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Captures plaster debris.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Sediment Interceptor",
    "category": "Plumbing",
    "tag_prefix": "SDI",
    "manufacturers": "Schier, Zurn, Josam",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Captures sediment.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Eye Wash Station",
    "category": "Plumbing",
    "tag_prefix": "EWS",
    "manufacturers": "Haws, Bradley, Guardian",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Emergency wash station.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Emergency Shower",
    "category": "Plumbing",
    "tag_prefix": "ES",
    "manufacturers": "Haws, Bradley, Guardian",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Emergency shower.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Sump Pump",
    "category": "Drainage",
    "tag_prefix": "SP",
    "manufacturers": "Liberty, Zoeller, Myers, Hydromatic, Little Giant, Flygt, Xylem, Barnes",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil / grease",
    "electrical_data": "120/208/460V",
    "description": "Pumps groundwater or clear water from sump pit to storm system.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Duplex Sump Pump",
    "category": "Drainage",
    "tag_prefix": "DSP",
    "manufacturers": "Liberty, Zoeller, Myers, Flygt, Hydromatic, Xylem",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 4.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil / grease",
    "electrical_data": "208/460V",
    "description": "Dual pump sump system with lead/lag control.",
    "semi_annual_std_hours": 2.0,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Storm Pump",
    "category": "Drainage",
    "tag_prefix": "STP",
    "manufacturers": "Liberty, Zoeller, Flygt, Myers, Xylem, Barnes",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil / grease",
    "electrical_data": "208/460V",
    "description": "Pumps storm water from basin or pit.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Sewage Pump",
    "category": "Drainage",
    "tag_prefix": "SWP",
    "manufacturers": "Liberty, Zoeller, Myers, Barnes, Flygt, Hydromatic",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil / grease",
    "electrical_data": "208/460V",
    "description": "Pumps sanitary waste from basin.",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Sump Basin",
    "category": "Drainage",
    "tag_prefix": "SB",
    "manufacturers": "Liberty, Zoeller, Orenco, Polylok, NDS",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Collection pit for sump water.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Sewage Basin",
    "category": "Drainage",
    "tag_prefix": "SEB",
    "manufacturers": "Liberty, Zoeller, Myers, Orenco, Polylok",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Basin for sanitary waste.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Catch Basin",
    "category": "Drainage",
    "tag_prefix": "CB",
    "manufacturers": "Zurn, NDS, ACO, Oldcastle, Contech, Mifab, Wade",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Collects surface runoff and debris.",
    "semi_annual_std_hours": 0.67,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Area Drain",
    "category": "Drainage",
    "tag_prefix": "AD",
    "manufacturers": "Zurn, Wade, Josam, Jay R Smith, Mifab",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Collects surface water at floor level.",
    "semi_annual_std_hours": 0.27,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Floor Drain",
    "category": "Drainage",
    "tag_prefix": "FD",
    "manufacturers": "Zurn, Wade, Josam, Jay R Smith, Mifab, Watts",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Drains floor water.",
    "semi_annual_std_hours": 0.27,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Floor Sink",
    "category": "Drainage",
    "tag_prefix": "FS",
    "manufacturers": "Zurn, Wade, Josam, Smith, Mifab",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Indirect waste receptor.",
    "semi_annual_std_hours": 0.27,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Trench Drain",
    "category": "Drainage",
    "tag_prefix": "TD",
    "manufacturers": "ACO, Zurn, Mifab, Watts, NDS, Polylok",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Linear floor drain for large areas.",
    "semi_annual_std_hours": 0.83,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Slot Drain",
    "category": "Drainage",
    "tag_prefix": "SD",
    "manufacturers": "ACO, Zurn, Mifab, Wade",
    "quarterly_std_hours": 0.2,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Narrow linear drain.",
    "semi_annual_std_hours": 0.63,
    "monthly_std_hours": 0.07
  },
  {
    "equipment_type": "Channel Drain",
    "category": "Drainage",
    "tag_prefix": "CD",
    "manufacturers": "ACO, Zurn, Mifab, NDS",
    "quarterly_std_hours": 0.2,
    "annual_std_hours": 1.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Surface drainage channel.",
    "semi_annual_std_hours": 0.63,
    "monthly_std_hours": 0.07
  },
  {
    "equipment_type": "Roof Drain",
    "category": "Drainage",
    "tag_prefix": "RD",
    "manufacturers": "Zurn, Wade, Josam, Jay R Smith, Mifab",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Drains roof storm water.",
    "semi_annual_std_hours": 0.35,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Overflow Roof Drain",
    "category": "Drainage",
    "tag_prefix": "ORD",
    "manufacturers": "Zurn, Wade, Josam, Smith",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Emergency roof drain.",
    "semi_annual_std_hours": 0.27,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Leader / Rainwater Leader",
    "category": "Drainage",
    "tag_prefix": "RL",
    "manufacturers": "pipe system",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Vertical storm pipe.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Cleanout",
    "category": "Drainage",
    "tag_prefix": "CO",
    "manufacturers": "Wade, Zurn, Josam, Smith, Mifab",
    "quarterly_std_hours": 0.05,
    "annual_std_hours": 0.25,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Access for cleaning.",
    "semi_annual_std_hours": 0.12,
    "monthly_std_hours": 0.02
  },
  {
    "equipment_type": "Backwater Valve",
    "category": "Drainage",
    "tag_prefix": "BWV",
    "manufacturers": "Mainline, Zurn, Josam, Canplas, Watts",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Prevents sewer backup.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Oil Water Separator",
    "category": "Drainage",
    "tag_prefix": "OWS",
    "manufacturers": "Highland Tank, Zurn, Mercer, Containment Solutions, ParkUSA",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 4.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Separates oil from water.",
    "semi_annual_std_hours": 1.83,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Sand Oil Interceptor",
    "category": "Drainage",
    "tag_prefix": "SOI",
    "manufacturers": "Zurn, Josam, Schier, Highland Tank",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Separates sand/oil.",
    "semi_annual_std_hours": 1.33,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Neutralization Basin",
    "category": "Drainage",
    "tag_prefix": "NB",
    "manufacturers": "Schier, Watts, Zurn, Josam",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Neutralizes acidic waste.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Storm Separator",
    "category": "Drainage",
    "tag_prefix": "SWS",
    "manufacturers": "Contech, CDS, Oldcastle, Stormceptor",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 4.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Stormwater treatment.",
    "semi_annual_std_hours": 1.83,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Rainwater Tank",
    "category": "Drainage",
    "tag_prefix": "RWT",
    "manufacturers": "Snyder, Xerxes, Norwesco, RainHarvest",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Stores rainwater.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Drainage Lift Station",
    "category": "Drainage",
    "tag_prefix": "DLS",
    "manufacturers": "Flygt, Xylem, Liberty, Zoeller, Myers",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 5.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "208/460V",
    "description": "Pumps drainage.",
    "semi_annual_std_hours": 2.33,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Manhole Pump Station",
    "category": "Drainage",
    "tag_prefix": "PS",
    "manufacturers": "Flygt, Xylem, Myers, Barnes",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 5.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "208/460V",
    "description": "Site pumping station.",
    "semi_annual_std_hours": 2.33,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "BAS Controller",
    "category": "Controls",
    "tag_prefix": "DDC",
    "manufacturers": "Johnson Controls, Siemens, Honeywell, Schneider, Delta Controls, Distech, Alerton, Reliable, Tridium",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V / 120V",
    "description": "Main building automation controller managing HVAC systems.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "BAS Panel",
    "category": "Controls",
    "tag_prefix": "CP",
    "manufacturers": "Johnson Controls, Siemens, Honeywell, Schneider, Delta, Distech, Reliable",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Control panel housing BAS hardware.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Network Controller",
    "category": "Controls",
    "tag_prefix": "NC",
    "manufacturers": "Tridium, JCI, Siemens, Honeywell, Schneider, Delta",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V / 120V",
    "description": "Supervisory controller for BAS network.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "VFD",
    "category": "Controls",
    "tag_prefix": "VFD",
    "manufacturers": "ABB, Danfoss, Yaskawa, Schneider, Siemens, Eaton, Allen Bradley, Toshiba",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "208/460V",
    "description": "Variable frequency drive for motor speed control.",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Thermostat",
    "category": "Controls",
    "tag_prefix": "T",
    "manufacturers": "Honeywell, Johnson Controls, Siemens, Schneider, Tekmar, Ecobee",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Space temperature control.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Space Sensor",
    "category": "Controls",
    "tag_prefix": "TS",
    "manufacturers": "Honeywell, Siemens, JCI, Schneider, Delta, Distech",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Measures room temperature.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Humidity Sensor",
    "category": "Controls",
    "tag_prefix": "HS",
    "manufacturers": "Honeywell, Vaisala, Siemens, JCI, Schneider",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Measures humidity.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Pressure Sensor",
    "category": "Controls",
    "tag_prefix": "PS",
    "manufacturers": "Honeywell, Ashcroft, Dwyer, Siemens, Setra",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Measures air or water pressure.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Differential Pressure Sensor",
    "category": "Controls",
    "tag_prefix": "DPS",
    "manufacturers": "Setra, Dwyer, Honeywell, Siemens, Ashcroft",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Used for filter / pump / airflow monitoring.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Flow Switch",
    "category": "Controls",
    "tag_prefix": "FS",
    "manufacturers": "McDonnell Miller, Taco, Dwyer, Gems, Honeywell",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Proves flow in piping.",
    "semi_annual_std_hours": 0.27,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Flow Meter",
    "category": "Controls",
    "tag_prefix": "FM",
    "manufacturers": "Onicon, Badger, Siemens, Krohne, Taco",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V / 120V",
    "description": "Measures water flow.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Motorized Damper",
    "category": "Controls",
    "tag_prefix": "MD",
    "manufacturers": "Belimo, Honeywell, Siemens, Ruskin, Greenheck, Nailor",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Modulates airflow.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Fire Damper",
    "category": "Controls",
    "tag_prefix": "FD",
    "manufacturers": "Ruskin, Greenheck, Nailor, Prefco, Halton",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Closes during fire event.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Smoke Damper",
    "category": "Controls",
    "tag_prefix": "SD",
    "manufacturers": "Ruskin, Greenheck, Nailor, Prefco, Halton",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Smoke control damper.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Fire Smoke Damper",
    "category": "Controls",
    "tag_prefix": "FSD",
    "manufacturers": "Ruskin, Greenheck, Nailor, Halton",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Combination damper.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Control Valve Actuator",
    "category": "Controls",
    "tag_prefix": "ACT",
    "manufacturers": "Belimo, Honeywell, Siemens, JCI, Danfoss",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Drives valve position.",
    "semi_annual_std_hours": 0.27,
    "monthly_std_hours": 0.05
  },
  {
    "equipment_type": "Gas Detector",
    "category": "Controls",
    "tag_prefix": "GD",
    "manufacturers": "Honeywell, Bacharach, MSA, RKI, Sensidyne",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Detects gas / CO / NO2.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "CO Sensor",
    "category": "Controls",
    "tag_prefix": "CO",
    "manufacturers": "Honeywell, Bacharach, Siemens, MSA",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Parking garage gas monitoring.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "NO2 Sensor",
    "category": "Controls",
    "tag_prefix": "NO2",
    "manufacturers": "Honeywell, Bacharach, Siemens",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Parking garage monitoring.",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Control Transformer",
    "category": "Controls",
    "tag_prefix": "XFMR",
    "manufacturers": "Square D, Eaton, Siemens, Schneider",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120/24V",
    "description": "Control power supply.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Relay Panel",
    "category": "Controls",
    "tag_prefix": "RP",
    "manufacturers": "Honeywell, Siemens, JCI, Schneider",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Switching panel.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Interface Module",
    "category": "Controls",
    "tag_prefix": "IM",
    "manufacturers": "Tridium, JCI, Siemens, Honeywell",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "BAS communication module.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "BACnet Gateway",
    "category": "Controls",
    "tag_prefix": "GW",
    "manufacturers": "Tridium, Schneider, Siemens, JCI",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Network integration device.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Time Clock",
    "category": "Controls",
    "tag_prefix": "TC",
    "manufacturers": "Intermatic, Honeywell, Siemens",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Schedules equipment.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Level Sensor",
    "category": "Controls",
    "tag_prefix": "LS",
    "manufacturers": "Gems, Dwyer, Siemens, Honeywell",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Measures tank level.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Float Switch",
    "category": "Controls",
    "tag_prefix": "FLS",
    "manufacturers": "SJE Rhombus, Dwyer, Gems, Liberty",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Controls pumps.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Alarm Panel",
    "category": "Controls",
    "tag_prefix": "AP",
    "manufacturers": "Honeywell, Siemens, Edwards, Notifier",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Equipment alarm monitoring.",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Fuel Oil Tank",
    "category": "Backup & Fuel",
    "tag_prefix": "FOT",
    "manufacturers": "Highland Tank, Granby, Roth, ZCL, Containment Solutions",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Stores fuel oil for boilers/generators",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Day Tank",
    "category": "Backup & Fuel",
    "tag_prefix": "DT",
    "manufacturers": "Highland Tank, Generac, Simplex, Titan",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Intermediate fuel tank",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Fuel Transfer Pump",
    "category": "Backup & Fuel",
    "tag_prefix": "FTP",
    "manufacturers": "Viking, Grundfos, Tuthill, Gorman Rupp",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "120/208V",
    "description": "Moves fuel between tanks",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Fuel Filter",
    "category": "Backup & Fuel",
    "tag_prefix": "FF",
    "manufacturers": "Racor, Parker, Baldwin, Fleetguard",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "cartridge",
    "filter_type": "cartridge",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Filters fuel",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Fuel Regulator",
    "category": "Backup & Fuel",
    "tag_prefix": "FR",
    "manufacturers": "Maxitrol, Fisher, Honeywell",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Controls fuel pressure",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Diesel Generator",
    "category": "Backup & Fuel",
    "tag_prefix": "GEN",
    "manufacturers": "Cummins, Caterpillar, Kohler, Generac, MTU",
    "quarterly_std_hours": 1.0,
    "annual_std_hours": 5.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Oil",
    "electrical_data": "480V",
    "description": "Backup power",
    "semi_annual_std_hours": 2.33,
    "monthly_std_hours": 0.33
  },
  {
    "equipment_type": "Generator Radiator",
    "category": "Backup & Fuel",
    "tag_prefix": "RAD",
    "manufacturers": "Cummins, CAT, Generac",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Generator cooling",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Side Stream Filter",
    "category": "Chemical Treatment",
    "tag_prefix": "SSF",
    "manufacturers": "Lakos, Eaton, Amiad, Parker",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "cartridge",
    "filter_type": "media",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Filters tower water",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Conductivity Controller",
    "category": "Chemical Treatment",
    "tag_prefix": "CC",
    "manufacturers": "Walchem, LMI, Neptune, Honeywell",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Controls bleed",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Chemical Pump",
    "category": "Chemical Treatment",
    "tag_prefix": "CHP",
    "manufacturers": "Pulsafeeder, LMI, Milton Roy",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Feeds chemicals",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Cooling Tower Basin Heater",
    "category": "Chemical Treatment",
    "tag_prefix": "BH",
    "manufacturers": "Indeeco, Chromalox, Watlow",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "480V",
    "description": "Prevent freezing",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Pool Pump",
    "category": "Pool",
    "tag_prefix": "PP",
    "manufacturers": "Pentair, Hayward, Sta-Rite, Goulds",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "208V",
    "description": "Circulates pool water",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Pool Filter",
    "category": "Pool",
    "tag_prefix": "PF",
    "manufacturers": "Pentair, Hayward, Sta-Rite",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "cartridge",
    "filter_type": "sand",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Filters pool water",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Pool Heater",
    "category": "Pool",
    "tag_prefix": "PH",
    "manufacturers": "Raypak, Lochinvar, Pentair, Laars",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "Gas",
    "description": "Heats pool",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Chlorine Feeder",
    "category": "Pool",
    "tag_prefix": "CLF",
    "manufacturers": "Pentair, Hayward, Pulsafeeder",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Chlorination",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "UV Pool Unit",
    "category": "Pool",
    "tag_prefix": "UV",
    "manufacturers": "Trojan, Wedeco, Viqua",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Disinfection",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Irrigation Pump",
    "category": "Irrigation",
    "tag_prefix": "IP",
    "manufacturers": "Grundfos, Goulds, Armstrong",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "208V",
    "description": "Pumps irrigation water",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Irrigation Controller",
    "category": "Irrigation",
    "tag_prefix": "IC",
    "manufacturers": "Rainbird, Hunter, Toro",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Controls watering",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Irrigation Backflow",
    "category": "Irrigation",
    "tag_prefix": "IBFP",
    "manufacturers": "Watts, Wilkins, Febco",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Prevent contamination",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Irrigation Valve",
    "category": "Irrigation",
    "tag_prefix": "IV",
    "manufacturers": "Rainbird, Hunter, Toro",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Zone control",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Air Compressor",
    "category": "Compressed Air",
    "tag_prefix": "AC",
    "manufacturers": "Atlas Copco, Quincy, Ingersoll Rand, Kaeser",
    "quarterly_std_hours": 0.75,
    "annual_std_hours": 3.0,
    "belt_size": "varies",
    "filter_size": "cartridge",
    "filter_type": "cartridge",
    "lubricant_type": "Oil",
    "electrical_data": "480V",
    "description": "Compressed air",
    "semi_annual_std_hours": 1.5,
    "monthly_std_hours": 0.25
  },
  {
    "equipment_type": "Air Dryer",
    "category": "Compressed Air",
    "tag_prefix": "AD",
    "manufacturers": "Hankison, Parker, Atlas Copco",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "cartridge",
    "filter_type": "cartridge",
    "lubricant_type": "",
    "electrical_data": "120V",
    "description": "Dries air",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Air Receiver",
    "category": "Compressed Air",
    "tag_prefix": "AR",
    "manufacturers": "Manchester, Worthington",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Stores air",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Air Filter",
    "category": "Compressed Air",
    "tag_prefix": "AF",
    "manufacturers": "Parker, SMC, Norgren",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "cartridge",
    "filter_type": "cartridge",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Filters air",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Snow Melt Pump",
    "category": "Radiant / Snowmelt",
    "tag_prefix": "SMP",
    "manufacturers": "Grundfos, Taco, Armstrong",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "208V",
    "description": "Circulates glycol",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Snow Melt Manifold",
    "category": "Radiant / Snowmelt",
    "tag_prefix": "SMM",
    "manufacturers": "Uponor, Viega, Watts",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Distributes loops",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Radiant Pump",
    "category": "Radiant / Snowmelt",
    "tag_prefix": "RP",
    "manufacturers": "Taco, Grundfos, Armstrong",
    "quarterly_std_hours": 0.5,
    "annual_std_hours": 2.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "Grease",
    "electrical_data": "208V",
    "description": "Radiant heat",
    "semi_annual_std_hours": 1.0,
    "monthly_std_hours": 0.17
  },
  {
    "equipment_type": "Radiant Manifold",
    "category": "Radiant / Snowmelt",
    "tag_prefix": "RM",
    "manufacturers": "Uponor, Viega, Watts",
    "quarterly_std_hours": 0.25,
    "annual_std_hours": 1.0,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Radiant distribution",
    "semi_annual_std_hours": 0.5,
    "monthly_std_hours": 0.08
  },
  {
    "equipment_type": "Pressure Gauge",
    "category": "Meters & Gauges",
    "tag_prefix": "PG",
    "manufacturers": "Ashcroft, Wika, Dwyer",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Pressure reading",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Temperature Gauge",
    "category": "Meters & Gauges",
    "tag_prefix": "TG",
    "manufacturers": "Ashcroft, Wika, Dwyer",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Temp reading",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Ball Valve",
    "category": "Valves",
    "tag_prefix": "BV",
    "manufacturers": "Apollo, Watts, Crane, Victaulic",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Isolation",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Butterfly Valve",
    "category": "Valves",
    "tag_prefix": "BFV",
    "manufacturers": "Victaulic, Bray, Keystone",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Isolation",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Check Valve",
    "category": "Valves",
    "tag_prefix": "CV",
    "manufacturers": "Watts, Apollo, Victaulic",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Prevent reverse",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Gate Valve",
    "category": "Valves",
    "tag_prefix": "GV",
    "manufacturers": "Crane, Nibco, Watts",
    "quarterly_std_hours": 0.1,
    "annual_std_hours": 0.5,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "",
    "description": "Isolation",
    "semi_annual_std_hours": 0.23,
    "monthly_std_hours": 0.03
  },
  {
    "equipment_type": "Solenoid Valve",
    "category": "Valves",
    "tag_prefix": "SV",
    "manufacturers": "ASCO, Honeywell, Parker",
    "quarterly_std_hours": 0.15,
    "annual_std_hours": 0.75,
    "belt_size": "",
    "filter_size": "",
    "filter_type": "",
    "lubricant_type": "",
    "electrical_data": "24V",
    "description": "Automatic valve",
    "semi_annual_std_hours": 0.35,
    "monthly_std_hours": 0.05
  }
];

export const CATEGORIES = [...new Set(EQUIPMASTER.map(e => e.category))].sort();

export function findEquipType(name) {
  const n = name.toLowerCase().trim();
  return EQUIPMASTER.find(e => e.equipment_type.toLowerCase() === n) ||
         EQUIPMASTER.find(e => n.includes(e.equipment_type.toLowerCase())) ||
         EQUIPMASTER.find(e => e.equipment_type.toLowerCase().includes(n));
}

export function getStdHours(equipType, frequency) {
  const e = findEquipType(equipType);
  if (!e) return null;
  const map = {
    monthly: e.monthly_std_hours,
    quarterly: e.quarterly_std_hours,
    "semi-annual": e.semi_annual_std_hours,
    annual: e.annual_std_hours,
  };
  return map[frequency] ?? e.quarterly_std_hours ?? null;
}